"""Speculative decoding utilities for MTP."""

import jax
import jax.numpy as jnp
from typing import Tuple, Optional, NamedTuple
from dataclasses import dataclass
from nanovllm_jax.config import Qwen3_5Config
from nanovllm_jax.mtp.mtp_layer import MTPParams


@dataclass
class SpeculativeState:
    """State for speculative decoding.
    
    Attributes:
        draft_tokens: Draft tokens generated by MTP [batch, num_drafts]
        draft_logits: Logits for draft tokens [batch, num_drafts, vocab_size]
        main_logits: Logits from main model verification [batch, num_drafts+1, vocab_size]
        acceptance_mask: Boolean mask of accepted tokens [batch, num_drafts]
        num_accepted: Number of accepted tokens per sequence [batch]
    """
    draft_tokens: jnp.ndarray
    draft_logits: jnp.ndarray
    main_logits: jnp.ndarray
    acceptance_mask: jnp.ndarray
    num_accepted: jnp.ndarray


def generate_draft_tokens(
    hidden_state: jnp.ndarray,
    confirmed_token_ids: jnp.ndarray,
    embed_tokens: jnp.ndarray,
    mtp_params: MTPParams,
    config: Qwen3_5Config,
    positions: Optional[jnp.ndarray] = None,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Generate draft tokens using MTP head.
    
    Args:
        hidden_state: Pre-norm hidden state from main model [batch, seq_len, hidden_size]
        confirmed_token_ids: Confirmed token IDs to use as input [batch, seq_len]
        embed_tokens: Token embedding table [vocab_size, hidden_size]
        mtp_params: MTP parameters
        config: Model config
        positions: Position IDs [batch, seq_len]
        
    Returns:
        Tuple of (draft_tokens, draft_logits)
        - draft_tokens: [batch, num_drafts]
        - draft_logits: [batch, num_drafts, vocab_size]
    """
    batch, seq_len, _ = hidden_state.shape
    
    # Get embedding of confirmed tokens
    confirmed_embed = embed_tokens[confirmed_token_ids]  # [batch, seq_len, hidden_size]
    
    # MTP forward pass to get draft logits
    draft_logits = mtp_params.mtp_forward(
        hidden_state=hidden_state,
        next_token_embed=confirmed_embed,
        params=mtp_params,
        config=config,
        positions=positions,
    )
    
    # Sample draft tokens (greedy for now)
    draft_tokens = jnp.argmax(draft_logits, axis=-1)  # [batch, seq_len]
    
    return draft_tokens, draft_logits


def verify_draft_tokens(
    confirmed_token_ids: jnp.ndarray,
    draft_tokens: jnp.ndarray,
    main_logits: jnp.ndarray,
    draft_logits: jnp.ndarray,
    temperature: float = 1.0,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Verify draft tokens against main model logits.
    
    Implements speculative decoding acceptance logic:
    1. Compute probabilities from main and draft logits
    2. Accept if draft token matches main model's sample
    3. Use rejection sampling for probabilistic acceptance
    
    Args:
        confirmed_token_ids: Confirmed tokens [batch, seq_len]
        draft_tokens: Draft tokens from MTP [batch, seq_len]
        main_logits: Logits from main model [batch, seq_len, vocab_size]
        draft_logits: Logits from MTP [batch, seq_len, vocab_size]
        temperature: Sampling temperature
        
    Returns:
        Tuple of (acceptance_mask, accepted_tokens)
        - acceptance_mask: [batch, seq_len] boolean
        - accepted_tokens: [batch, seq_len] tokens to use
    """
    # Compute probabilities
    main_probs = jax.nn.softmax(main_logits / temperature, axis=-1)
    draft_probs = jax.nn.softmax(draft_logits / temperature, axis=-1)
    
    # Gather probabilities for draft tokens
    batch_size, seq_len = draft_tokens.shape
    batch_indices = jnp.arange(batch_size)[:, None]
    seq_indices = jnp.arange(seq_len)[None, :]
    
    draft_token_probs = main_probs[batch_indices, seq_indices, draft_tokens]
    
    # Acceptance probability: min(1, main_prob / draft_prob)
    # This is the standard speculative decoding acceptance ratio
    acceptance_prob = jnp.minimum(
        1.0,
        draft_token_probs / (jnp.where(draft_probs[batch_indices, seq_indices, draft_tokens] > 0, 
                                        draft_probs[batch_indices, seq_indices, draft_tokens], 
                                        1e-10))
    )
    
    # Sample acceptance (for non-greedy)
    if temperature > 0:
        acceptance_noise = jax.random.uniform(jax.random.PRNGKey(0), (batch_size, seq_len))
        acceptance_mask = acceptance_noise < acceptance_prob
    else:
        # Greedy: accept if draft matches main argmax
        main_tokens = jnp.argmax(main_logits, axis=-1)
        acceptance_mask = (draft_tokens == main_tokens)
    
    # Accepted tokens are draft tokens where mask is True
    accepted_tokens = jnp.where(acceptance_mask, draft_tokens, confirmed_token_ids)
    
    return acceptance_mask, accepted_tokens


def apply_acceptance(
    seq_tokens: jnp.ndarray,
    draft_tokens: jnp.ndarray,
    acceptance_mask: jnp.ndarray,
    num_drafts: int = 1,
) -> Tuple[jnp.ndarray, int]:
    """Apply acceptance mask to update sequence.
    
    For K=1 (single draft):
    - If accepted: append draft token
    - If rejected: sample from main model residual
    
    Args:
        seq_tokens: Current sequence tokens [batch, seq_len]
        draft_tokens: Draft tokens [batch, num_drafts]
        acceptance_mask: Acceptance mask [batch, num_drafts]
        num_drafts: Number of draft tokens (K)
        
    Returns:
        Tuple of (updated_tokens, num_accepted)
    """
    batch_size, seq_len = seq_tokens.shape
    
    # For K=1, simple case
    if num_drafts == 1:
        accepted = acceptance_mask[:, 0]  # [batch]
        
        # Tokens to append: draft if accepted, else will be resampled
        tokens_to_append = jnp.where(
            accepted[:, None],
            draft_tokens[:, 0:1],
            jnp.zeros((batch_size, 1), dtype=jnp.int32)  # Placeholder, will be resampled
        )
        
        # Append to sequence
        updated_tokens = jnp.concatenate([seq_tokens, tokens_to_append], axis=1)
        
        num_accepted = accepted.sum()
        
        return updated_tokens, num_accepted
    
    # For K>1, more complex logic (TODO: implement later)
    # For now, just handle K=1
    raise NotImplementedError("K>1 speculative decoding not yet implemented")
